# Generated by Django 5.0.2 on 2024-03-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0002_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
