# Generated by Django 5.0.2 on 2024-03-07 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0004_userlogin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_tag', models.CharField(help_text='Telegram group tag to monitor, e.g., @rgb_rostov_events', max_length=100)),
                ('keywords', models.CharField(help_text='Keywords to search for, separated by commas', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parser_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
