# Generated by Django 4.1.7 on 2024-05-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0005_telegramgroup_channel_id"),
        ("telegram_auth", "0006_auto_20240516_2328"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parsersetting",
            name="parser",
        ),
        migrations.AddField(
            model_name="parsersetting",
            name="city",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parser_settings",
                to="saite.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parsersetting",
            name="keywords",
            field=models.TextField(
                default=2, help_text="Введите ключевые слова, разделенные запятыми"
            ),
            preserve_default=False,
        ),
    ]
