# Generated by Django 4.1.7 on 2024-05-18 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "telegram_auth",
            "0007_remove_parsersetting_parser_parsersetting_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsersetting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parser_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
