# Generated by Django 3.2.25 on 2024-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_tag', models.CharField(max_length=255)),
                ('keywords', models.TextField(help_text='Введите ключевые слова, разделенные запятыми')),
            ],
        ),
    ]
