# Generated by Django 3.2.25 on 2024-05-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saite', '0003_auto_20240516_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='group',
        ),
        migrations.AddField(
            model_name='parser',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parsers', to='saite.city'),
            preserve_default=False,
        ),
    ]
