# Generated by Django 4.1.7 on 2024-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0004_auto_20240516_2311"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="channel_id",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
