# Generated by Django 4.1.7 on 2024-05-18 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0005_telegramgroup_channel_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Parser",
        ),
    ]
